# Generated by Django 2.2.5 on 2019-09-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('time_absence', models.DateField()),
                ('time_apply', models.DateField(auto_now_add=True)),
                ('result', models.CharField(default='Not processed yet!', max_length=300)),
                ('permission', models.BooleanField(default=False)),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applier', to='Orchestral.Identity')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='Orchestral.Identity')),
            ],
            options={
                'unique_together': {('applier', 'time_absence')},
            },
        ),
    ]
